### ISSUE TITLE
Add Swoole\\Coroutine\\PostgreSQL

### ISSUE THREAD

**Issue by Jurigag** [swoole/ide-helper#15]
As i see https://github.com/swoole/ext-postgresql is missing here, could you add it?

Well actually for 4.3.3 stubs it is here, but for 4.3.4 is removed, even it's still part of core as i see here - https://github.com/swoole/swoole-src/tree/v4.3.4 it's presented `swoole_postgresql_coro.cc` or i miss something?

**Comment by deminy** [comment]
In new versions of Swoole some features have been moved to separate projects, e.g, [ext-serialize](https://github.com/swoole/ext-serialize), [ext-postgresql](https://github.com/swoole/ext-postgresql). I should be able to have stubs for them added later this month. Thanks

**Comment by deminy** [comment]
This has been added in latest release [4.4.3](https://github.com/swoole/ide-helper/releases/tag/4.4.3).
