### ISSUE TITLE
inconsistency between helper and documentation, Coroutine/Client::close()

### ISSUE THREAD

**Issue by Druid33** [swoole/ide-helper#25]
HI,

first, thanks for this helper. Its really usefull.

I found one inconsisteny between helper and documentation. 

In swoole documentation there is one parameter for coroutine client close function: https://www.swoole.co.uk/docs/modules/swoole-coroutine-client-close

But in ide helper this function is without parameter. 
![image](https://user-images.githubusercontent.com/6436809/119037364-2ae68600-b9b2-11eb-8f6f-ad4d6a0a0306.png)

Its bug or feature? :)

**Comment by deminy** [comment]
Hello Peter. Please note that the documentation is not always up to date. It's better to refer to this IDE Helper package for class/method definitions of latest versions of Swoole.

Thanks

**Comment by doubaokun** [comment]
@Druid33 the param is removed recently, the docs is fixed now. Thanks for reporting.

**Comment by Druid33** [comment]
@deminy thanks for info. You say "its better to refer to IDE Helper package". but i dont know...

Now I fixing bug with channels and i found this:

Ide helper says:
![image](https://user-images.githubusercontent.com/6436809/119107088-39b75200-ba1f-11eb-968e-a8f4fa6a8432.png)

documentation say:
![image](https://user-images.githubusercontent.com/6436809/119107243-56ec2080-ba1f-11eb-9947-a62142ed58e0.png)

````php
I make some test on my own:
// all this channels has capacity 1
new Channel();
new Channel(0);
new Channel(-1);
new Channel(-2);

// this thrown: Fatal error: Uncaught TypeError: Swoole\Coroutine\Channel::__construct(): Argument #1 ($size) must be of type int, null given
new Channel(null);

// this channels has capacity 1000
new Channel(1000);
````

So in this case, documentation is different from ide helper and both are inaccurate.

I dont blame you or swoole team, your work is awesome. Just its frustrating using swoole, when official documentation is so brief , outdated and inconsistence with ide helper.

**Comment by doubaokun** [comment]
@Druid33 the documentation is generally up to date except some minimum issues. We are working on improving it every week.

It doesn't make sense to create a channel with capacity less than 1.

**Comment by sy-records** [comment]
I think you should see #19 @Druid33
