### ISSUE TITLE
`tick` method is missing from Swoole\WebSocket\Server

### ISSUE THREAD

**Issue by TorstenDittmann** [swoole/ide-helper#26]
The `tick($ms, $callback)` method is missing from the __Swoole\WebSocket\Server__ class.

**Comment by sy-records** [comment]
No `ticket` method. Only [tick](https://www.swoole.co.uk/docs/modules/swoole-server-tick), it is available, but it is available.

**Comment by TorstenDittmann** [comment]
Sorry, typo - I was talking about the `tick` method that is missing from the ide-helper library 👍🏻

**Comment by sy-records** [comment]
Yes, it exists only as an alias. https://www.swoole.co.uk/docs/modules/swoole-timer-tick

**Comment by TorstenDittmann** [comment]
![Bildschirmfoto 2021-06-24 um 11 53 24](https://user-images.githubusercontent.com/1759475/123242953-d3709400-d4e2-11eb-9186-6c73b320a700.png)
![Bildschirmfoto 2021-06-24 um 11 53 10](https://user-images.githubusercontent.com/1759475/123242955-d4092a80-d4e2-11eb-92a2-ca58e8247e18.png)

If these 2 are the same, it would be helpful to have this covered as well in the `ide-helper` classes 🙂 
That way an IDE wouldn't complain about a missing `tick` method on the Server class.

**Comment by deminy** [comment]
Added in commit https://github.com/swoole/ide-helper/commit/ac92c32e033978bf7a41cabaca60802b6750938a .
