### ISSUE TITLE
可以对以前添加的函数、方法添加 @since 来标记起始版本号吗

### ISSUE THREAD

**Issue by crazywhalecc** [swoole/ide-helper#34]
鉴于 Swoole 更新频率较快，新增函数直接上文档，而文档本身只会对绝大部分后面新加的内容标注，且不易查找和区分。相反，是否可以通过 ide-helper 的 @since 注解来快速判断此功能是否兼容旧版？

看起来工作量不小，但是我闲着的话应该也能帮帮忙。或者觉得有必要这样做吗？

**Comment by deminy** [comment]
`@since` 自版本4.8.0以来已经开始使用, 此后新加的函数等都使用了该标记。例如, https://github.com/swoole/ide-helper/blob/master/src/swoole/Swoole/Coroutine.php#L76

欢迎提交PR。PR不一定要是文档注释（英文）方面的，可以是各种错误修复、格式优化、标记优化等等，哪怕是小的改进都是好的。谢谢
