### ISSUE TITLE
Update ide-helper to 5.1.3

### ISSUE THREAD

**Issue by haeber** [swoole/ide-helper#36]
Hi, I am already running Swoole 5.1.3 with ide-helper 5.1.2, but not 100% sure it's fully compatible. Therefore I've created this issue, with the wish that you either update/bump the ide-helper to 5.1.3, too, or feel free to close this issue, because everything works perfectly with Swoole 5.1.3.

Kind Regards
Thomas

See https://github.com/swoole/swoole-src/releases/tag/v5.1.3

**Comment by deminy** [comment]
Package `swoole/ide-helper` has been updated to [5.1.3](https://github.com/swoole/ide-helper/releases/tag/5.1.3). Please feel free to let us know any questions. Thanks

**Comment by haeber** [comment]
> Package `swoole/ide-helper` has been updated to [5.1.3](https://github.com/swoole/ide-helper/releases/tag/5.1.3). Please feel free to let us know any questions. Thanks

Thanks a lot!
